Feat/visualize square with centered letter
awotawa/dojoWordle pull request #2
Opened 2022-12-07 16:54 UTC by awotawa

I can see a square with a letter

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/71437974/206241466-44acc4b0-3db2-4819-aead-7bc21df52392.png">

2022-12-07 17:59 UTC, LouisKraemer requested changes

2022-12-07 17:59 UTC, LouisKraemer commented on dojoWordle/.eslintrc.js
> +};
Elle vient d'où toute cette config ?

2022-12-07 17:59 UTC, LouisKraemer commented on dojoWordle/.prettierrc
> +}
Pourquoi on met prettier ?

2022-12-07 17:59 UTC, LouisKraemer commented on dojoWordle/babel.config.js
> -    presets: ['babel-preset-expo'],
Pourquoi on rajoute ce preset babel ?

2022-12-07 17:59 UTC, LouisKraemer commented on dojoWordle/jest.config.js
> +module.exports = config;
Tu peux m'expliquer ce fichier demain ?

2022-12-07 17:59 UTC, LouisKraemer commented on dojoWordle/jest/utils/renderWithProviders.tsx
> +// </SafeAreaProvider>
Pourquoi on a des commentaires de SafeProvider ? On ne le veut plus ?

2022-12-07 17:59 UTC, LouisKraemer commented on dojoWordle/package.json
> +    "jest-watch-typeahead": "^2.2.1",
C'est quoi ce paquet ?

2022-12-07 17:59 UTC, LouisKraemer commented on dojoWordle/src/shared/services/theme/typography.ts
> +    fontSize: fontSizes.XS,
On a besoin de tout ça ?

2022-12-07 17:59 UTC, LouisKraemer commented on dojoWordle/src/components/Game.test.tsx
> +});
Si je mets deux fois la lettre A dans mon clavier et que je supprimer le composant LetterBox, est-ce que mon test est vert ou rouge ?

2022-12-08 08:46 UTC, awotawa commented on dojoWordle/.eslintrc.js
> +};
https://github.com/bamlab/react-native-enabler/blob/master/docs/enable_my_application/development_tools_options/linter/options/eslint.md

2022-12-08 09:22 UTC, LouisKraemer approved these changes

2022-12-08 13:49 UTC, LouisKraemer commented on dojoWordle/src/components/LetterBox.tsx
> +  | 'enter'
enter et del c'est pas possible si ? Et string vide non plus je crois

2022-12-08 13:50 UTC, LouisKraemer commented on dojoWordle/jest.config.js
>    // setupFiles: ['./jest/test-setup.js'],
On peut enlever si code commenté

2022-12-08 13:50 UTC, LouisKraemer commented on dojoWordle/src/components/Game.test.tsx
> +// expect.extend({ toHaveStyle, toHaveProp });
Pareil

2022-12-08 13:51 UTC, LouisKraemer commented on dojoWordle/src/components/Game.test.tsx
> +    ]);
Je supprimerai cet expect et à la place je ferai un test unitaire snapshot de Letterbox avec la props validity dans tous les états possibles

2022-12-08 13:52 UTC, LouisKraemer commented on dojoWordle/src/components/Game.test.tsx
> +    ]);
Pareil

2022-12-08 13:55 UTC, LouisKraemer commented on dojoWordle/src/components/Game.tsx
> +const checkValidity = (
Pour moi on devrait pas avoir deux states. Les deux states sont liés donc la valeur validity devrait être dérivée du state letter

2022-12-08 15:59 UTC, LouisKraemer commented on dojoWordle/src/components/LetterBox.tsx
> +      {letter !== null && <TextContainer>{letter.toUpperCase()}</TextContainer>}
Ca me semble plus lisible si c'est une ternaire

2022-12-08 16:08 UTC, LouisKraemer approved these changes

2022-12-08 16:09 UTC, merged